version: '3.7'

services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'engine-db'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: ./
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/engine-db?autoReconnect=true&useSSL=false
    depends_on:
      - db
    volumes:
      - .:/code

volumes:
  mysql-data: