name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  CD:
    name: CD Pipeline
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven package
        run: cd engine; chmod +x mvnw; ./mvnw clean package -DskipTests
      - name: Maven verify 
        run: cd engine; ./mvnw clean verify
      - name: Deploy docker-compose
        run: cd engine; docker-compose up -d --build
      - name: Check if containers are running
        run: docker ps 
